const express = require('express')
const app = express()
require('./config/mongoose.config')
require('./models/producer.model')
const cors = require('cors')
app.use(cors())
app.use(express.json(), express.urlencoded({extended: true}))
const blogRoutes = require('./routes/blog.route')
app.use('/public/', express.static('public'))
blogRoutes(app)
app.listen(8000, () => console.log('Server is connected on port 8000'))