import styles from './layout.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head';
import Navbar from './navbar';
import Sidebar from './sidebar';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.left}>
          <Sidebar/>
        </div>
        <div className={styles.right}>
          <Navbar/>
          {children}
        </div>
        
      </body>
    </html>
  )
}
